admin_id:
  - 731704898633


TOKEN: "...."
license : "....."

mikrotik_ip: "1.1.1.1"
username: "user"
password: "pass"

listp:
  - name: "paln"
    price: 35
    text: "text"


testP: "TEST"

ovpn_test_file: "OpenVPN.ovpn"
open_file: "OpenVPN.ovpn"

text_user_test: ""
text_user: ""

base_name: "user"

pass_panel: "admin_pass"

text_main_menu: |
  Ø³Ù„Ø§Ø§Ø§Ù… Ø¨Ù‡ Ø±Ø¨Ø§Øª  VPN Ø®ÙˆØ´ Ø§ÙˆÙ…Ø¯ÛŒ ğŸ«¡ğŸŒ¸

  Ù…Ø§ Ø§ÛŒÙ†Ø¬Ø§ÛŒÛŒÙ… ØªØ§ Ø´Ù…Ø§ Ø±Ø§ Ø¨Ø¯ÙˆÙ† Ù‡ÛŒÚ† Ù…Ø­Ø¯ÙˆÛŒØªÛŒ Ø¨Ù‡ Ø´Ø¨Ú©Ù‡ Ø¬Ù‡Ø§Ù†ÛŒ Ù…ØªØµÙ„ Ú©Ù†ÛŒÙ…

  ğŸ“¡ Ø¨Ø±Ù‚Ø±Ø§ÛŒ Ø§Ù…Ù†ÛŒØª Ø¯Ø± Ø§Ø±ØªØ¨Ø§Ø· Ø´Ù…Ø§
  â˜ï¸ Ù¾Ø´ØªÛŒØ¨Ø§Ù†ÛŒ ØªØ§ Ø±ÙˆØ² Ø¢Ø®Ø±

username_admin: "@vpn"
